AWSTemplateFormatVersion: "2010-09-09"
Description: Create a IAM role policy and profile for EC2 Instance full access
Resources:
  Ec2AccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
  RolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "Ec2Access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "ec2:*"
            Resource: "*"
          -
            Effect: "Allow"
            Action: "elasticloadbalancing:*"
            Resource: "*"
          -
            Effect: "Allow"
            Action: "cloudwatch:*"
            Resource: "*"
          -
            Effect: "Allow"
            Action: "autoscaling:*"
            Resource: "*"
      Roles:
        -
          Ref: "Ec2AccessRole"
  EC2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        -
          Ref: "Ec2AccessRole"
Outputs:
  Profile:
    Value: !Ref EC2InstanceProfile
    Description: Information about the IAM Profile
