AWSTemplateFormatVersion: "2010-09-09"
Description: Create a Security Group template
Resources:
  Ec2AccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      RoleName: EC2_full_access_role
  RolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "Ec2Access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "ec2:*"
            Resource: "*"
      Roles:
        -
          Ref: "Ec2AccessRole"
  RootInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        -
          Ref: "Ec2AccessRole"
Outputs:
  Profile:
    Value: !Sub Ec2InstanceProfile
    Description: Information about the IAM Profile
