AWSTemplateFormatVersion: "2010-09-09"
Description: Create a Security Group template
Resources:
  ChildStackVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/lavinia-dev-nested/VPC.json
      TimeoutInMinutes: 50
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow-ssh
      VpcId: !GetAtt ChildStackVPC.Outputs.VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
Outputs:
  VPC:
    Value: !GetAtt ChildStackVPC.Outputs.VPC
    Description: Information about the VPC
  SecurityGroup:
    Value: !Sub SecurityGroup
    Description: Information about the SecurityGroup
